base_config: configs/acoustic.yaml

raw_data_dir:
  - data/opencpop/raw
speakers:
  - opencpop
spk_ids: []
test_prefixes:
  - '2091003368'
  - '2092003408'
  - '2093003449'
  - '2094003484'
  - '2095003518'
dictionary: dictionaries/opencpop.txt
binary_data_dir: data/acoustic/binary
binarization_args:
  num_workers: 4
pe: parselmouth
pe_ckpt: null
vocoder: NsfHifiGAN
vocoder_ckpt: checkpoints/nsf_hifigan_44.1k_hop512_128bin_2024.02/model.ckpt

use_spk_id: false
num_spk: 1
use_energy_embed: false
use_breathiness_embed: false
use_voicing_embed: false
use_tension_embed: false
use_key_shift_embed: false
use_speed_embed: false

augmentation_args:
  random_pitch_shifting:
    enabled: false
    range: [-5., 5.]
    scale: 0.75
  fixed_pitch_shifting:
    enabled: false
    targets: [-5., 5.]
    scale: 0.5
  random_time_stretching:
    enabled: false
    range: [0.5, 2.]
    scale: 0.75

residual_channels: 512
residual_layers: 20

# shallow diffusion
use_shallow_diffusion: true
# K_step: 250
K_step_infer: 250
shallow_diffusion_args:
  train_aux_decoder: true
  train_diffusion: true
  val_gt_start: false
  aux_decoder_arch: convnext
  aux_decoder_args:
    num_channels: 512
    num_layers: 6
    kernel_size: 7
    dropout_rate: 0.1
  aux_decoder_grad: 0.1
lambda_aux_mel_loss: 0.2

optimizer_args:
  lr: 0.0006
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 30000
  gamma: 0.5
max_batch_frames: 50000
max_batch_size: 64
max_updates: 50000

num_valid_plots: 10
val_with_vocoder: true
val_check_interval: 2000
num_ckpt_keep: 10
permanent_ckpt_start: 120000
permanent_ckpt_interval: 20000
pl_trainer_devices: 'auto'
pl_trainer_precision: '16-mixed'
